name: Read project config
description: Finds project IDs by environment

inputs:
  cwd:
    description: Relative path to use for searching. Defaults to repo root. Will search upwards for config_file.
    required: true
    default: .
  config_file:
    description: Which file that contains the project config. Defaults to "projects.config.json".
    required: true
    default: projects.config.json

runs:
  using: composite
  steps:
    - name: Read project config
      id: read_project_config
      working-directory: ${{ inputs.cwd }}
      shell: bash
      run: |
        search_up() {
            local look=${PWD%/}
        
            while [[ -n $look ]]; do
            [[ -e $look/$1 ]] && {
            printf '%s\n' "$look"
            return
            }
            
            look=${look%/*}
            done
        
            [[ -e /$1 ]] && echo /
        }
        CONFIG_FILE=$(search_up "${{ inputs.config_file }}")
        if [ -f "$CONFIG_FILE" ]; then
          echo ::set-output name=project_ids_by_environment::$(cat $CONFIG_FILE)
        fi

outputs:
  project_ids_by_environment:
    description: Project IDs by environment (as stringified JSON)
    value: ${{ steps.read_project_config.outputs.project_ids_by_environment }}