name: Read project config
description: Finds project IDs by environment

inputs:
  cwd:
    description: Relative path to use for searching. Defaults to repo root. Will search upwards for config_file.
    required: true
    default: .
  config_file:
    description: Which file that contains the project config. Defaults to "projects.config.json".
    required: true
    default: projects.config.json

runs:
  using: composite
  steps:
    - name: Verify that the code has been checked out
      working-directory: .
      shell: bash
      run: |
        if [ ! -d .git ]; then
          echo "ERROR: Code must be checked out first"
          exit 1
        fi
        
    - name: Read project config
      id: read_project_config
      working-directory: ${{ inputs.cwd }}
      shell: bash
      run: |
        FILE="${{ inputs.config_file }}"
        if ! [ -f "$FILE" ]; then
          CONFIG_FILE=$(DIR=`pwd`
            while [ "$DIR" != "/" ] ; do
              DIR=`dirname "$DIR"`
              find "$DIR" -maxdepth 1 -name "$FILE"
            done
          )
        else
          CONFIG_FILE="$FILE"
        fi
        if [ -f "$CONFIG_FILE" ]; then
          echo ::set-output name=project_ids_by_environment::$(cat $CONFIG_FILE)
        fi

outputs:
  project_ids_by_environment:
    description: Project IDs by environment (as stringified JSON)
    value: ${{ steps.read_project_config.outputs.project_ids_by_environment }}