name: Read project config
description: Finds project IDs by environment

inputs:
  cwd:
    description: Relative path to use for searching. Defaults to repo root. Will search upwards for config_file.
    required: true
    default: .
  config_file:
    description: Which file that contains the project config. Defaults to "projects.config.json".
    required: true
    default: projects.config.json
  required:
    description: Whether action should fail if no config file is found.
    required: false
    default: 'false'

runs:
  using: node16
  main: ./index.js

outputs:
  project_ids_by_environment:
    description: Project IDs by environment (as stringified JSON)
