name: Build and upload Gradle module

on:
  workflow_call:
    inputs:
      storage_bucket:
        description: The GCP storage bucket into which to upload artifacts.
        type: string
        required: true
      app_root:
        description: Path to source code project from root of Git repo
        type: string
        required: true
      destination_path:
        description: Path within storage bucket where to upload artifact. Defaults to `app_root`.
        type: string
        required: false
        default: ""
      version_property:
        description: Project property used to set app version
        required: false
        type: string
        default: appVersion
      app_version:
        description: Will set the app version of the JAR to be built and published
        required: false
        type: string
        default: ${{ github.run_number }}
      ref:
        description: Which ref to create release for. Defaults to same as workflow is run from if empty.
        required: false
        type: string
        default: ${{ github.sha }}
      gradlew_path:
        description: Relative path to the gradle wrapper. Defaults to `../gradlew`.
        type: string
        required: false
        default: ../gradlew
      publish_glob:
        description: Glob pattern to match artifacts to publish. Defaults to `*.zip`.
        type: string
        required: false
        default: "*.zip"
      shared_project_config_root:
        description: Relative path to the shared project config root (where the projects.config.json for the team shared project can be found). Defaults to repo root.
        type: string
        required: false
        default: "."
    secrets:
      storage_bucket_sa_publisher_key:
        description: Service account key used to publish JAR to artifact bucket. If not set, attempts to use Workload Identity Federation with shared project ID from `projects.config.json` in shared_project_config_root.
        required: false

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  REF: ${{ github.inputs.ref }}

jobs:
  build_module:
    name: Build module and publish
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.app_root }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ env.REF }}

      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build function
        run: ${{ inputs.gradlew_path }} shadowJar -P${{ inputs.version_property }}=${{ inputs.app_version }}

      - name: Zip jars
        run: find . -type f -name "*.jar" -exec bash -c 'zip -j `basename {}`.zip {}' \;

      - name: Setup Google Cloud SDK
        uses: svvsaga/github-actions-public/setup-gcloud-with-json-key@v12.0.0
        with:
          app_root: ${{ inputs.shared_project_config_root }}
          environment: SHARED
          service_account_key: ${{ secrets.storage_bucket_sa_publisher_key }}

      - name: Publish to GCS
        uses: google-github-actions/upload-cloud-storage@v0
        with:
          path: ${{ inputs.app_root }}
          destination: ${{ inputs.storage_bucket }}/${{ inputs.destination_path || inputs.app_root }}
          glob: ${{ inputs.publish_glob }}
          parent: false
          gzip: false