name: Generate docs

on:
  push:
    branches:
      - main
    paths:
      - "**/action.yml"
  workflow_dispatch:

jobs:
  generate-docs:
    name: Generate docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: find . -iname action.yml -execdir sh -c 'action-docs > README.md' \;