name: Publish Terraform plans
on:
  workflow_call:
    inputs:
      ref:
        description: Which commit, tag or branch to plan terraform from. Defaults to same as workflow is run from if empty.
        required: false
        type: string
      app_root:
        description: Path to source code project from root of Git repo
        type: string
        required: true
      release_id:
        description: ID of GitHub release, typically output from actions/create-release
        type: string
        required: true
      storage_bucket_stm:
        description: Storage bucket for Terraform plan in STM (tries to use projects.config.json if not set)
        type: string
        required: false
      storage_bucket_atm:
        description: Storage bucket for Terraform plan in ATM (tries to use projects.config.json if not set)
        type: string
        required: false
      storage_bucket_prod:
        description: Storage bucket for Terraform plan in PROD (tries to use projects.config.json if not set)
        type: string
        required: false

    secrets:
      github_app_private_key:
        description: Private key for GitHub application to get app token
        required: true
      github_app_id:
        description: GitHub application ID to get app token
        required: true
      service_account_key_stm:
        description: Service account key to use with `gcloud` for STM. If not set, attempts to use workload identity federation from projects.config.json.
        required: false
      service_account_key_atm:
        description: Service account key to use with `gcloud` for ATM. If not set, attempts to use workload identity federation from projects.config.json.
        required: false
      service_account_key_prod:
        description: Service account key to use with `gcloud` for PROD. If not set, attempts to use workload identity federation from projects.config.json.
        required: false
      terraform_vars:
        description: Additional variables for Terraform in .tfvar-format with quotes escaped and newlines, e.g. 'foo = \"abc\"\nbar = \"def\"'
        required: false

jobs:
  read_config:
    name: Read project config
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.ref }}

      - name: Read project config
        id: read_config
        uses: svvsaga/github-actions-public/read-project-config@v8.10.2
        with:
          cwd: ${{ inputs.app_root }}
    outputs:
      project_ids_by_environment: ${{ steps.read_config.outputs.project_ids_by_environment }}

  publish_plans:
    permissions:
      contents: 'read'
      id-token: 'write'
    name: Publish Terraform plans
    runs-on: ubuntu-latest
    needs: [ read_config ]
    strategy:
      fail-fast: false
      matrix:
        environment: [ STM, ATM, PROD ]
        include:
          - environment: STM
            sa_key_secret: service_account_key_stm
            storage_bucket: ${{ inputs.storage_bucket_stm || format('svv-{0}', fromJson(needs.read_config.outputs.project_ids_by_environment).STM) }}
          - environment: ATM
            sa_key_secret: service_account_key_atm
            storage_bucket: ${{ inputs.storage_bucket_atm || format('svv-{0}', fromJson(needs.read_config.outputs.project_ids_by_environment).ATM) }}
          - environment: PROD
            sa_key_secret: service_account_key_prod
            storage_bucket: ${{ inputs.storage_bucket_prod || format('svv-{0}', fromJson(needs.read_config.outputs.project_ids_by_environment).PROD) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.ref }}

      - name: Setup Google Cloud SDK
        uses: svvsaga/github-actions-public/setup-gcloud@v8.10.2
        with:
          service_account_key: ${{ secrets[matrix.sa_key_secret] }}
          app_root: ${{ inputs.app_root }}
          environment: ${{ matrix.environment }}

      - name: Get app token
        id: get_token
        uses: tibdex/github-app-token@36464acb844fc53b9b8b2401da68844f6b05ebb0
        with:
          private_key: ${{ secrets.github_app_private_key }}
          app_id: ${{ secrets.github_app_id }}

      - name: Set GitHub token
        run: |
          git config --global url."https://x-access-token:${{ steps.get_token.outputs.token }}@github.com".insteadOf https://github.com
          echo "GITHUB_TOKEN=${{ steps.get_token.outputs.token }}" >> $GITHUB_ENV

      - name: Publish plan for ${{ matrix.environment }}
        uses: svvsaga/github-actions-public/publish-terraform-plan-to-gcs@v8.4.0
        with:
          environment: ${{ matrix.environment }}
          project_root: ${{ inputs.app_root }}
          storage_bucket: ${{ matrix.storage_bucket }}
          release_id: ${{ inputs.release_id }}
          terraform_vars: ${{ secrets.terraform_vars }}
